# Generated by Django 4.1.5 on 2023-01-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at'], 'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
    ]
