# Generated by Django 4.1.5 on 2023-01-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
