# Generated by Django 4.1.5 on 2023-01-06 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('guest_limit', models.PositiveSmallIntegerField(verbose_name='Guest limit')),
                ('bathrooms', models.PositiveSmallIntegerField(verbose_name='Bathrooms')),
                ('accept_pets', models.BooleanField(verbose_name='Accept pets')),
                ('cleaning_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cleaning price')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Activation date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
